name: Code testing
run-name: Code testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get test program
        run: |
          cd ${{ github.workspace }}/src
          wget https://github.com/Extraskilled56/Echo-kernel/raw/main/build-test/build-test
          chmod +x build-test
      - name: Get enviroment ready
        run: |
          cd ${{ github.workspace }}/src
          sudo apt full-upgrade -y
          sudo apt install gcc nasm -y
          mkdir tmp
      - name: build
        run: |
          cd ${{ github.workspace }}/src
          ./build-test

          
