name: Code testing
run-name: Code testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get enviroment ready
        run: |
          cd ${{ github.workspace }}/src
          mkdir tmp
      - name: build
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build.sh
  publish-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build ISO
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build-iso-actions.sh
      - name: Upload ISO
        run: |
         cd ${{ github.workspace }}/src
         git clone --depth 1 -b iso https://github.com/Extraskilled56/Echo-kernel.git
         git config user.name "Echo bot"
         git config user.email "echo@echo.com"
         mv *.iso Echo-kernel/Echo-kernel-$ECHO_VERSION.iso
         cd Echo-kernel
         git add *.iso
         git commit -m "Add iso"
         git push --force
          
