name: Code testing
run-name: Code testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get enviroment ready
        run: |
          cd ${{ github.workspace }}/src
          mkdir tmp
          sudo apt install gh -y
      - name: build
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build.sh
  upload-iso:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Setup node first
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.1.0
        with:
          access-token: ${{ secrets.ACCESS }}
          file-path: ${{ github.workspace }}/src/Echo-kernel-0.0.2.iso
          owner: Extraskilled56
          repo: Echo-kernel
          branch-name: iso
          commit-message: add iso
