name: Code testing
run-name: Code testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get enviroment ready
        run: |
          cd ${{ github.workspace }}/src
          sudo apt install gcc nasm -y
          mkdir tmp
      - name: build
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build.sh

          