name: Code testing
run-name: Code testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get enviroment ready
        run: |
          cd ${{ github.workspace }}/src
          mkdir tmp
          sudo apt install gh -y
      - name: build
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build.sh
  publish-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build ISO
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build-iso-actions.sh
      - name: Upload ISO
        run: |
         git config --global user.email "zacharyj@bitsyncdev.com"
         git config --global user.name "bit-bot56"
         cd ${{ github.workspace }}/src
         git clone --depth 1 -b iso https://github.com/Extraskilled56/Echo-kernel.git
         mv *.iso Echo-kernel/Echo-kernel-$ECHO_VERSION.iso
         cd Echo-kernel
         echo "${{ secrets.GH_TOKEN }}" > mytoken.txt
         gh auth login --with-token < mytoken.txt
         git add *.iso
         git commit -m "Add iso"
         git push --force
         
