name: Code testing
run-name: Code testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get enviroment ready
        run: |
          cd ${{ github.workspace }}/src
          sudo apt install gcc nasm -y
          mkdir tmp
      - name: build
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build.sh
  publish-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build ISO
        run: |
          cd ${{ github.workspace }}/src
          bash scripts/build-iso.sh
      - name: Upload ISO
        run: |
         cd ~/
         git clone --depth 1 -b iso https://github.com/Extraskilled56/Echo-kernel.git
         cd Echo-kernel
         git config user.name "Echo bot"
         git config user.email "echo@echo.com"
         echo $ECHO-VERSION
          
